### ISSUE TITLE
document : ajout d'item supprime le texte

### ISSUE THREAD

**Issue by paulgirard** [medialab/aime-core#178]
Dans un document.
Créer une slide.
Ajouter du texte.
Ajouter une ressource.
Save

Charger un autre document.
Recharger le document créé => le text avant la ressource inséré dans la slide a disparu.

EDIT :
Une ressource ne peut pas être entouré de texte sans ligne vide immédiatement avant ou après.

Pourquoi pas mais ce n'est pas visible dans l'interface et le texte disparaît sans prévenir.

**Comment by Yomguithereal** [comment]
J'ai changé la manière dont l'éditeur insère les items pour améliorer ça.
