### ISSUE TITLE
Faire le tour des updates de resources

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/aime-core#205]

**Comment by Yomguithereal** [comment]
Link Check

**Comment by paulgirard** [comment]
si le contenu html change car l'url change par exemple dans une vidéo, il faut recharger la preview.

**Comment by paulgirard** [comment]
on ne peut pas changer un fichier pdf. Est ce nécessaire ? 
Peut être ajouter un delete ressource un jour...
